Train:
  batch_size: 128
  learning_rate: 0.01
  reg: 0.0005
  epochs: 10
  steps: [6, 8]
  warmup: 0
  momentum: 0.9
  reweight: False
  beta: 0
network:
  model: ResNet-32

data:
  imbalance: imbalance
  save_best: True

loss:
  loss_type: CE # CE or Focal