Train:
  batch_size: 128
  learning_rate: 0.003
  reg: 0.0005
  epochs: 10
  steps: [6, 8]
  warmup: 0
  momentum: 0.9

network:
  model: MyModel 

data:
  imbalance: regular 
  save_best: True

loss:
  loss_type: CE
